### ISSUE TITLE
Add to Awesome Google Cloud Platform

### ISSUE THREAD

**Issue by bcoe** [zrosenbauer/awesome-bigtable#12]
My colleagues pointed out this list to me:

https://github.com/GoogleCloudPlatform/awesome-google-cloud

It seems like it would be good to add Awesome Bigtable here.

**Comment by zrosenbauer** [comment]
Resolved by https://github.com/GoogleCloudPlatform/awesome-google-cloud/pull/27

**Comment by zrosenbauer** [comment]
Completed.
